//--------------------  USUARIOS --------------------------//

### Hacer Login
POST https://aliadasapp-c7b7f9ab639b.herokuapp.com/api/users/login
Content-Type: application/json

{
    "email": "maomur@gmail.com",
    "password": "maomur"
}

### Listar todos los usuarios
GET http://localhost:3330/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6Ik1hdXJpY2lvIiwiZXhwX2RhdGUiOjE2OTY2MTQ0NTgsInJvbGwiOiJhZG1pbiIsImlhdCI6MTY5NjYxMjY1OH0.q2DpEN9Ol4X1nMs45yElODXD03onrkqreCOpn7yo128

### Listar usuario por ID
GET http://localhost:3330/api/users/9
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6Ik1hdXJpY2lvIiwiZXhwX2RhdGUiOjE2OTY2MTQ0NTgsInJvbGwiOiJhZG1pbiIsImlhdCI6MTY5NjYxMjY1OH0.q2DpEN9Ol4X1nMs45yElODXD03onrkqreCOpn7yo128


### Ver usuario por email
GET http://localhost:3330/api/users/email/maomur@gmail.com
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6Ik1hdXJpY2lvIiwiZXhwX2RhdGUiOjE2OTY2MTQ0NTgsInJvbGwiOiJhZG1pbiIsImlhdCI6MTY5NjYxMjY1OH0.q2DpEN9Ol4X1nMs45yElODXD03onrkqreCOpn7yo128

### Crear usuario
POST https://aliadasapp-c7b7f9ab639b.herokuapp.com/api/users/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6Ik1hdXJpY2lvIiwiZXhwX2RhdGUiOjE2OTg1OTI2NDMsInJvbGwiOiJhZG1pbiIsImlhdCI6MTY5ODU5MDg0M30.WsMQRPuMwQVizEQWLgQ4GQPLEVp6vEqPYpkpNAbPYKk

{
    "name": "Escuela",
    "lastname": "Admin",
    "email": "otros@ens.org.co",
    "city": "Barcelona",
    "roll": "admin",
    "fecha_nacimiento": "Septiembre 10",
    "mobil": "87776556",
    "password": "2023",
    "isDelete": 0
}

### Eliminar Usuario
GET http://localhost:3330/api/users/delete/4

### Actualizar usuario
PUT http://localhost:3330/api/users/update/4
Content-Type: application/json

{
    "name": "Mauricio",
    "lastname": "Requena",
    "email": "emma@gmail.com",
    "city": "Barcelona",
    "roll": "Empleado",
    "fecha_nacimiento": "Septiembre 10",
    "mobil": "87776556",
    "password": "emma",
    "isDelete": 0
}


