//--------------  SEGURIDAD SOCIAL ------------------//

### Listar Contenido
GET http://localhost:3330/api/seguridad/1

### Actualizar por Id
PUT http://localhost:3330/api/seguridad/update/1
Content-Type: application/json

{
    "descripcion": "seguridad Ok",
    "titulo_1": "¿Qué leyes protegen a las mujeres que sufren de violencia y acoso en el lugar de trabajo?",
    "texto_1": "a) A nivel internacionalEl convenio 190 de la Organización Internacional del Trabajo OIT- sobre violencia y acoso en el lugar del trabajo del año 2019, está pendiente por ser ratificado o aprobado por la ley colombiana, aun así, es un precedente importante para identificar y denunciar la violencia de la que puedes ser víctima en tu lugar de trabajo.",
    "titulo_2": "Tipos de Acoso",
    "texto_2": "texto 2",
    "titulo_3": "Estas son algunas situaciones o conductas que se consideran acoso laboral según la ley",
    "texto_3": "texto 3",
    "titulo_4": "Violencias hacía las trabajadoras domésticas",
    "texto_4": "texto 4",
    "titulo_5": "¿Qué hacer en caso de ser víctima de violencia en el lugar de trabajo?",
    "texto_5": "texto 5",
    "titulo_6": "Recuerda que, en caso de violación sexual, como víctima tienes derecho a que:",
    "texto_6": "texto 6",
    "titulo_7": "¿Cómo me cuido de ser víctima de violencia en mi lugar de trabajo?",
    "texto_7": "texto 7",
    "titulo_8": "Instancias territoriales para la denuncia de violencias",
    "texto_8": "",
    "titulo_9": "",
    "texto_9": "",
    "titulo_10": "",
    "texto_10": "",
    "titulo_11": ""
}